DROP DATABASE IF EXISTS DBESTAMPARIA;
CREATE DATABASE DBESTAMPARIA;
USE DBESTAMPARIA;

CREATE TABLE `DBESTAMPARIA`.`PESSOA` (
`ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `CPF` VARCHAR(15) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `SENHA` VARCHAR(255) NOT NULL,
  `FUNCIONARIO` TINYINT NOT NULL,
  PRIMARY KEY (`ID`));
  
  
CREATE TABLE `DBESTAMPARIA`.`PEDIDO`(
	`ID` INT NOT NULL AUTO_INCREMENT,
    `STATUS_PEDIDO` VARCHAR(20) NOT NULL,
    `ID_PESSOA` INT NULL,
    `DATA` DATE NOT NULL,
    PRIMARY KEY (`ID`),
	CONSTRAINT ID_PESSOA
    FOREIGN KEY (ID_PESSOA)
    REFERENCES DBESTAMPARIA.PESSOA (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

  
CREATE TABLE `DBESTAMPARIA`.`CAMISA`(
	`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `TAMANHO` CHAR(4) NOT NULL,
    `COR` VARCHAR(20) NOT NULL,
    `ESTAMPA` blob NOT NULL,
    `NOMEARQUIVO` varchar(40) NOT NULL,
    `ID_PEDIDO` INT NOT NULL,
	CONSTRAINT ID_PEDIDO
    FOREIGN KEY (ID_PEDIDO)
    REFERENCES DBESTAMPARIA.PEDIDO (id)
 );

INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('ELIEZER','22222222222', 'ELIEZER@GMAIL.COM','FUNCI', TRUE);
INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('RAQUEL','11111111111', 'RAQUEL@GMAIL.COM','FUNCI', TRUE);
INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('LOUISE','11111231151', 'LOUISE@GMAIL.COM','FUNCI', TRUE);
INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('JULIA','11113341111', 'JULIA@GMAIL.COM','CLIEN', FALSE);
INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('MARCOS','11113341231', 'MARCOS@GMAIL.COM','CLIEN', FALSE);
INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('ROBERTO','11133341231', 'ROBERTO@GMAIL.COM','CLIEN', FALSE);
INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('LUCIANA','12113341231', 'LUCIANA@GMAIL.COM','CLIEN', FALSE);
INSERT INTO PESSOA (NOME,CPF,EMAIL,SENHA,FUNCIONARIO) VALUES ('LUCAS','15113341231', 'LUCAS@GMAIL.COM','CLIEN', FALSE);




SELECT * FROM PESSOA;
SELECT * FROM PEDIDO;
SELECT * FROM CAMISA;
select count(*) from pessoa  where email = 'ELIEZERLIZ2704@GMAIL.COM';
SELECT ID, EMAIL, SENHA, FUNCIONARIO from pessoa where email like 'ELIEZERLIZ2704@GMAIL.COM' and senha like 'abc' ;